name: Sarkari Alerts Auto-Scraper

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch: 

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # 👈 इसे v3 से v4 कर दिया गया है

    - name: Set up Python
      uses: actions/setup-python@v5  # 👈 इसे v4 से v5 कर दिया गया है
      with:
        python-version: '3.10'

    - name: Install Libraries
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Python Script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
      run: python scraper.py

    - name: Save updated jobs.json back to GitHub
      run: |
        git config --global user.name "m2j247-bot"
        git config --global user.email "bot@sarkarialerts.com"
        git add jobs.json
        git commit -m "Auto-updated latest jobs" || exit 0
        git push
